version: '3'

services:
  shortie:
    image: ghcr.io/reesericci/shortie-server:latest
    env_file: .env
    ports:
      - 3000:3000
      - 31337:31337
    links:
      - redis
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    command: redis-server --requirepass password

